In [1]:
import pandas as pd;

In [5]:
print(pd.__version__)

3.0.5

In [8]:
import os

os.listdir(r"C:\Users\Om\Downloads")

['.opera',
 'Aadhar.jpeg',
 'Antigravity-x64.exe',
 'Blinkit Analysis.pbix',
 'cc_add.csv.csv',
 'Certificate_SC-B3D23A2305.png',
 'ChatGPT Image Oct 1, 2026, 12_13_40 PM.png',
 'Coffee+Shop+Sales',
 'Credit Card Dashboard.html',
 'credit-dashboard',
 'credit-dashboard.zip',
 'credit_card.csv.csv',
 'credit_card_import.sql',
 'Credit_Card_report.dashboardpdf.pdf',
 'Credit_Card_report.dpdf.pdf',
 'customer.csv.csv',
 'cust_add.csv.csv',
 'desktop.ini',
 'Excel.certificate.jpeg',
 'features.csv',
 'features.csv.zip',
 'fn datasets',
 'gcs logo.jpeg',
 'gcs.2.jpeg',
 'gcs.logo.2.jpeg',
 'hackindia.intership-main (4)',
 'hackindia.intership-main (4).zip',
 'intership.project',
 'Khilender_Rajput B.tech(AI) 2027.pdf',
 'kr.photo.1.jpeg',
 'kr.photo.2.jpeg',
 'leetcode.badges.jpeg',
 'Minimal Pastel Dashboard Background.png',
 'mysql-connector-net-26.7.0',
 'mysql-connector-net-26.7.0 (1).msi',
 'mysql-connector-net-26.7.0.msi',
 'mysql-connector-net-26.7.0.zip',
 'mysql-installer-community-8.0.46.0.msi',
 'postgresql-16.15-4-windows-x64.exe',
 'sampleSubmission.csv.zip',
 'sql.certificate.jpeg',
 'Sql.project.live',
 'stores.csv',
 'test.csv',
 'test.csv.zip',
 'train.csv',
 'train.csv.zip',
 'Walmart.csv']

In [11]:
df = pd.read_csv(r"C:\Users\Om\Downloads\Walmart.csv")
df.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [15]:
df.shape

(10051, 11)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [14]:
df.duplicated().sum()

np.int64(51)

In [18]:
df.drop_duplicates(inplace = True)
df.shape

(10000, 11)

In [19]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [20]:
# Dropping all missing values
df.dropna(inplace = True)

In [21]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [22]:
df.shape

(9969, 11)

In [23]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [30]:
df['unit_price'] = df['unit_price'].str.replace("$","")

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [32]:
df["unit_price"] = df["unit_price"].astype(float)

In [33]:
df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

In [36]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [38]:
df['total'] = df['unit_price']* df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [39]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-py2.py3-none-any.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-py2.py3-none-any.whl (480 kB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [46]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="Khilender@2026"
)

print("Connected successfully!")

Connected successfully!

In [ ]:
cursor = conn.cursor()

cursor.execute("SHOW DATABASES")

for db in cursor:
    print(db[0])

In [47]:
cursor = conn.cursor()

In [48]:
cursor.execute("CREATE DATABASE walmart")
print("Database created successfully!")

Database created successfully!

In [54]:
import sys
print(sys.executable)

\\?\C:\Users\Om\AppData\Roaming\jupyterlab-desktop\jlab_server\python.exe

In [50]:
cursor.execute("USE walmart")
print("walmart selected!")

walmart selected!

In [56]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "SQLAlchemy"
])

0

In [57]:
import sqlalchemy

print(sqlalchemy.__version__)

2.1.3

In [62]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("Khilender@2026")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/walmart"
)

print("Engine created successfully!")

Engine created successfully!

In [60]:
import sqlalchemy
print(sqlalchemy.__version__)

2.1.3

In [63]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("khilender@2026")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/walmart"
)

print("Engine created successfully!")

Engine created successfully!

In [66]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="Walmart@2026"
)

print("MySQL connected!")

MySQL connected!

In [67]:
cursor = conn.cursor()

cursor.execute("SHOW DATABASES")

for db in cursor:
    print(db[0])

information_schema
mysql
performance_schema
sakila
sys
walmart
world

In [68]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("Walmart@2026")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/walmart"
)

In [69]:
with engine.connect() as connection:
    print("SQLAlchemy connected!")

SQLAlchemy connected!

In [70]:
df.to_sql(
    "walmart_sales",
    con=engine,
    if_exists="replace",
    index=False
)

print("Walmart data imported successfully!")

Walmart data imported successfully!

In [71]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM walmart_sales",
    con=engine
)

   total_rows
0        9969

In [72]:
pd.read_sql(
    "SELECT * FROM walmart_sales LIMIT 5",
    con=engine
)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17